[SP-10441] Update RFID result type
regulaforensics/DocumentReader-web-openapi pull request #120
Opened 2023-07-07 12:12 UTC by dangost

2023-07-07 14:06 UTC, vyakimchik commented on rt.yml
> +        - "RAW_DATA"
```suggestion
        - "RFID_RAW_DATA"
```

2023-07-07 14:06 UTC, vyakimchik commented on rt.yml
> +        - "BINARY_DATA"
```suggestion
        - "RFID_BINARY_DATA"
```

2023-07-07 14:06 UTC, vyakimchik commented on rt.yml
> +        - "ORIGINAL_GRAPHICS"
```suggestion
        - "RFID_ORIGINAL_GRAPHICS"
```

2023-07-17 13:18 UTC, vyakimchik commented on rt.yml
> +        - "ervers for storing the results of data reading in a form of a list of objects of the original binary representation of the graphics in memory of the RFID-chip"
```suggestion
        - "Servers for storing the results of data reading in a form of a list of objects of the original binary representation of the graphics in memory of the RFID-chip"
```

2023-07-17 13:20 UTC, vyakimchik approved these changes

2023-07-17 14:58 UTC, vyakimchik commented on rt.yml
> +        - "Servers for storing the data reading results from the RFID-chip in a form of a list of the logically separated data groups"
```suggestion
        - "Servers for storing the data reading results from the RFID-chip in a form of a list of the logically separated data groups (raw data)"
```

2023-07-17 15:00 UTC, vyakimchik commented on rt.yml
> +        - "Servers for storing the data reading results from the RFID-chip in a form of a list of the logically separated data groups"
```suggestion
        - "Servers for storing the data reading results from the RFID-chip in a form of a list of the logically separated data groups (binary data)"
```

2023-07-17 15:22 UTC, vyakimchik approved these changes

2023-07-18 09:18 UTC, ikliashchou requested changes

2023-07-18 09:18 UTC, ikliashchou commented on rt.yml
> +        - "RFID_RAW_DATA"
а чего еще два пропустили с текстовыми и графическими данными?

2023-07-18 09:18 UTC, ikliashchou commented on rt.yml
> +        - "Servers for storing the results of data reading in a form of a list of objects of the original binary representation of the graphics in memory of the RFID-chip"
Needs rewriting
"Servers"? Make Contains as everywhere else
I cannot understand the description at all this way

2023-07-19 15:24 UTC, ikliashchou approved these changes

2023-07-19 15:30 UTC, merged