SP-19172 - add format field to RawImageContainer
regulaforensics/DocumentReader-web-openapi pull request #202
Opened 2024-10-24 08:39 UTC by inspector-code

2024-11-14 16:28 UTC, ikliashchou requested changes

2024-11-14 16:28 UTC, ikliashchou commented on p-ping.yml
> +                $ref: "#/components/schemas/DeviceInfoDeprecated"
why?

2024-11-14 16:28 UTC, ikliashchou commented on rt-raw-image.yml
>      DocumentImageResult:
this is all wrong
this should be the same type for both RPRM_ResultType_RawUncroppedImage =16 and RPRM_ResultType_RawImage = 1 results.

2024-11-15 11:42 UTC, vyakimchik commented on rt-raw-image.yml
> +        Most of coordinates in other types defined on that image"
```suggestion
      description: "Contains document images after processing."
```

2024-11-16 09:00 UTC, ikliashchou commented on rt-raw-image.yml
> +      description: "Contains document images after processing."
```suggestion
      description: "Contains document image."
```

2024-11-16 09:05 UTC, ikliashchou approved these changes

2024-11-16 09:05 UTC, merged