SP-19555: Add imageUrls
regulaforensics/DocumentReader-web-openapi pull request #207
Opened 2024-11-13 12:26 UTC by GubinAlexander

2024-11-14 12:27 UTC, KirylKovaliov approved these changes

2024-11-14 15:51 UTC, ikliashchou requested changes

2024-11-14 15:51 UTC, ikliashchou commented on p-process.yml
> +        ImageUrls:
description missing

2024-11-16 08:48 UTC, ikliashchou commented on p-process.yml
> +          description: "URL to the document image for processing."
```suggestion
          description: "URLs to the document images for processing."
```

2024-11-16 08:48 UTC, ikliashchou approved these changes

2024-11-16 08:58 UTC, merged