SP-19158: Add DTC
regulaforensics/DocumentReader-web-openapi pull request #208
Opened 2024-11-13 13:26 UTC by GubinAlexander

2024-11-13 18:38 UTC, KirylKovaliov approved these changes

2024-11-14 15:39 UTC, ikliashchou requested changes

2024-11-14 15:39 UTC, ikliashchou commented on p-process.yml
> +          description: "This parameter is used to generate DTC-VC"
```suggestion
          description: "This parameter is used to generate separate DTC-VC data container from RFID session data."
```

2024-11-14 15:39 UTC, ikliashchou commented on rt-image-data.yml
> +    DTCVCResult:
looks incomplete, please recheck

2024-11-14 15:54 UTC, ikliashchou commented on rt.yml
> +      $ref: "./rt-image-data.yml#/components/schemas/DTCVCResult"
wrong yaml file, should be separate

2024-11-19 12:53 UTC, merged