rl-36/text-field-type TextFieldType:
regulaforensics/DocumentReader-web-openapi pull request #40
Opened 2020-10-26 09:40 UTC by alshund

- add 596-624 text field type without description

2020-10-26 09:41 UTC, alshund commented
resolve #36

2020-10-26 09:41 UTC, alshund commented
@ikliashchou а может есть описания для данных типов?

2020-10-28 10:26 UTC, hleb-albau requested changes

2020-10-28 10:26 UTC, hleb-albau commented on e-text-field-type.yml
> +        - 'DLCLASSCODE_LR_FROM'
let's name it  DL_CLASSCODE_** (see other DL examples)
DL - driver license (also, add description as other DL classes)

2020-11-03 13:07 UTC, merged